#########################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza      #
#      SPDX-License-Identifier:  GPL-2.0-only                           #
#########################################################################
# aws cloudformation create-stack --stack-name ocp-installer --template-body file://policy.yaml --capabilities CAPABILITY_IAM

---

AWSTemplateFormatVersion: "2010-09-09"

Description: This template creates a policy, a role and a user to install OCP

Resources:

  Group:
    DependsOn: ManagedPolicy
    ManagedPolicyArns:
    - !Ref ManagedPolicy
    Type: AWS::IAM::Group

  ManagedPolicy:
    Properties:
      PolicyDocument:
        Statement:
        - 
          Effect: Allow
          Action:
          - ec2:AuthorizeSecurityGroupEgress
          - ec2:AuthorizeSecurityGroupIngress
          - ec2:CreateNetworkInterface
          - ec2:CreateSecurityGroup
          - ec2:CreateTags
          - ec2:CreateVolume
          - ec2:DeleteSecurityGroup
          - ec2:DeleteSnapshot
          - ec2:RevokeSecurityGroupEgress
          - ec2:RevokeSecurityGroupIngress
          - ec2:RunInstances
          - ec2:TerminateInstances
          Resource: 
          - "arn:aws:ec2:*:*:capacity-reservation/*"
          - "arn:aws:ec2:*:*:client-vpn-endpoint/*"
          - "arn:aws:ec2:*:*:dedicated-host/*"
          - "arn:aws:ec2:*:*:dhcp-options/*"
          - "arn:aws:ec2:*:*:egress-only-internet-gateway/*"
          - "arn:aws:ec2:*:*:elastic-gpu/*"
          - "arn:aws:ec2:*:*:export-instance-task/*"
          - "arn:aws:ec2:*:*:fleet/*"
          - "arn:aws:ec2:*::fpga-image/*"
          - "arn:aws:ec2:*:*:key-pair/*"
          - "arn:aws:ec2:*::image/*"
          - "arn:aws:ec2:*:*:instance/*"
          - "arn:aws:ec2:*:*:internet-gateway/*"
          - "arn:aws:ec2:*:*:launch-template/*"
          - "arn:aws:ec2:*:*:local-gateway/*"
          - "arn:aws:ec2:*:*:local-gateway-route-table/*"
          - "arn:aws:ec2:*:*:local-gateway-route-table-virtual-interface-group-association/*"
          - "arn:aws:ec2:*:*:local-gateway-route-table-vpc-association/*"
          - "arn:aws:ec2:*:*:local-gateway-virtual-interface/*"
          - "arn:aws:ec2:*:*:local-gateway-virtual-interface-group/*"
          - "arn:aws:ec2:*:*:natgateway/*"
          - "arn:aws:ec2:*:*:network-acl/*"
          - "arn:aws:ec2:*:*:network-interface/*"
          - "arn:aws:ec2:*:*:placement-group/*"
          - "arn:aws:ec2:*:*:reserved-instances/*"
          - "arn:aws:ec2:*:*:route-table/*"
          - "arn:aws:ec2:*:*:security-group/*"
          - "arn:aws:ec2:*::snapshot/*"
          - "arn:aws:ec2:*:*:spot-instances-request/*"
          - "arn:aws:ec2:*:*:subnet/*"
          - "arn:aws:ec2:*:*:traffic-mirror-filter/*"
          - "arn:aws:ec2:*:*:traffic-mirror-session/*"
          - "arn:aws:ec2:*:*:traffic-mirror-target/*"
          - "arn:aws:ec2:*:*:transit-gateway/*"
          - "arn:aws:ec2:*:*:transit-gateway-attachment/*"
          - "arn:aws:ec2:*:*:transit-gateway-multicast-domain/*"
          - "arn:aws:ec2:*:*:transit-gateway-route-table/*"
          - "arn:aws:ec2:*:*:volume/*"
          - "arn:aws:ec2:*:*:vpc/*"
          - "arn:aws:ec2:*:*:vpc-endpoint/*"
          - "arn:aws:ec2:*:*:vpc-endpoint-service/*"
          - "arn:aws:ec2:*:*:vpc-flow-log/*"
          - "arn:aws:ec2:*:*:vpn-connection/*"
          - "arn:aws:ec2:*:*:vpn-gateway/*"
          - "arn:aws:elastic-inference:*:*:elastic-inference-accelerator/*"
        - 
          Effect: Allow
          Action:
          - ec2:AllocateAddress
          - ec2:AssociateAddress
          - ec2:CopyImage
          - ec2:AttachNetworkInterface
          - ec2:DeregisterImage
          - ec2:DescribeAccountAttributes
          - ec2:DescribeAddresses
          - ec2:DescribeAvailabilityZones
          - ec2:DescribeDhcpOptions
          - ec2:DescribeImages
          - ec2:DescribeInstanceAttribute
          - ec2:DescribeInstanceCreditSpecifications
          - ec2:DescribeInstances
          - ec2:DescribeInternetGateways
          - ec2:DescribeKeyPairs
          - ec2:DescribeNatGateways
          - ec2:DescribeNetworkAcls
          - ec2:DescribeNetworkInterfaces
          - ec2:DescribePrefixLists
          - ec2:DescribeRegions
          - ec2:DescribeRouteTables
          - ec2:DescribeSecurityGroups
          - ec2:DescribeSubnets
          - ec2:DescribeTags
          - ec2:DescribeVolumes
          - ec2:DescribeVpcAttribute
          - ec2:DescribeVpcClassicLink
          - ec2:DescribeVpcClassicLinkDnsSupport
          - ec2:DescribeVpcEndpoints
          - ec2:DescribeVpcs
          - ec2:GetEbsDefaultKmsKeyId
          - ec2:ModifyInstanceAttribute
          - ec2:ModifyNetworkInterfaceAttribute
          - ec2:ReleaseAddress
          Resource: '*'
        - 
          Effect: Allow
          Action:
          - "ec2:CreateDhcpOptions"
          - "ec2:CreateInternetGateway"
          - "ec2:CreateNatGateway"
          - "ec2:CreateRoute"
          - "ec2:CreateSubnet"          
          - "ec2:CreateVpc"
          - "ec2:CreateVpcEndpoint"
          Resource:
          - "arn:aws:ec2:*:*:dhcp-options/*"
          - "arn:aws:ec2:*:*:internet-gateway/*"
          - "arn:aws:ec2:*:*:natgateway/*"
          - "arn:aws:ec2:*:*:route-table/*"
          - "arn:aws:ec2:*:*:security-group/*"
          - "arn:aws:ec2:*:*:subnet/*"
          - "arn:aws:ec2:*:*:vpc/*"
          - "arn:aws:ec2:*:*:vpc-endpoint/*"
        - 
          Effect: Allow
          Action:
          - "ec2:AssociateDhcpOptions",
          - "ec2:CreateRouteTable",
          - "ec2:AttachInternetGateway",
          - "ec2:ModifyVpcAttribute",
          - "ec2:AssociateRouteTable",
          - "ec2:ModifySubnetAttribute"
          Resource: '*'
        - 
          Effect: Allow
          Action:
          - elasticloadbalancing:AddTags
          - elasticloadbalancing:ApplySecurityGroupsToLoadBalancer
          - elasticloadbalancing:AttachLoadBalancerToSubnets
          - elasticloadbalancing:ConfigureHealthCheck
          - elasticloadbalancing:CreateLoadBalancer
          - elasticloadbalancing:CreateLoadBalancerListeners
          - elasticloadbalancing:DeleteLoadBalancer
          - elasticloadbalancing:DeregisterInstancesFromLoadBalancer
          - elasticloadbalancing:ModifyLoadBalancerAttributes
          - elasticloadbalancing:RegisterInstancesWithLoadBalancer
          - elasticloadbalancing:SetLoadBalancerPoliciesOfListener
          Resource: arn:aws:elasticloadbalancing:*:*:loadbalancer/*
        - 
          Effect: Allow
          Action:
          - elasticloadbalancing:DescribeInstanceHealth
          - elasticloadbalancing:DescribeListeners
          - elasticloadbalancing:DescribeLoadBalancerAttributes
          - elasticloadbalancing:DescribeLoadBalancers
          - elasticloadbalancing:DescribeTags
          - elasticloadbalancing:DescribeTargetGroupAttributes
          - elasticloadbalancing:DescribeTargetHealth
          Resource: '*'
        - 
          Effect: Allow
          Action:
          - elasticloadbalancing:CreateListener
          - elasticloadbalancing:CreateTargetGroup
          - elasticloadbalancing:DeregisterTargets
          - elasticloadbalancing:ModifyTargetGroup
          - elasticloadbalancing:ModifyTargetGroupAttributes
          - elasticloadbalancing:RegisterTargets
          Resource: 
          - arn:aws:elasticloadbalancing:*:*:targetgroup/*/*
          - arn:aws:elasticloadbalancing:*:*:loadbalancer/app/*/*
          - arn:aws:elasticloadbalancing:*:*:loadbalancer/net/*/*
        - 
          Effect: Allow
          Action:
          - iam:AddRoleToInstanceProfile
          - iam:CreateInstanceProfile
          - iam:CreateRole
          - iam:DeleteInstanceProfile
          - iam:DeleteRole
          - iam:DeleteRolePolicy
          - iam:GetInstanceProfile
          - iam:GetRole
          - iam:GetRolePolicy
          - iam:GetUser
          - iam:ListInstanceProfilesForRole
          - iam:PassRole
          - iam:PutRolePolicy
          - iam:RemoveRoleFromInstanceProfile
          - iam:SimulatePrincipalPolicy
          - iam:TagRole
          Resource:
          - "arn:aws:iam::*:group/*"
          - "arn:aws:iam::*:instance-profile/*"
          - "arn:aws:iam::*:role/*"
          - "arn:aws:iam::*:user/*"
        - 
          Effect: Allow
          Action:
          - iam:ListRoles
          - iam:ListUsers
          Resource: '*'
        - 
          Effect: Allow
          Action:
          - route53:ChangeResourceRecordSets
          - route53:ChangeTagsForResource
          - route53:DeleteHostedZone
          - route53:GetChange
          - route53:GetHostedZone
          - route53:ListResourceRecordSets
          - route53:ListTagsForResource
          - route53:UpdateHostedZoneComment
          Resource:
          - "arn:aws:route53:::change/*"
          - "arn:aws:route53:::healthcheck/*"
          - "arn:aws:route53:::hostedzone/*"
        - 
          Effect: Allow
          Action:
          - route53:CreateHostedZone
          - route53:ListHostedZones
          - route53:ListHostedZonesByName
          Resource: '*'
        - 
          Effect: Allow
          Action:
          - s3:CreateBucket
          - s3:DeleteBucket
          - s3:GetAccelerateConfiguration
          - s3:GetBucketAcl
          - s3:GetBucketCors
          - s3:GetBucketLocation
          - s3:GetBucketLogging
          - s3:GetBucketObjectLockConfiguration
          - s3:GetBucketReplication
          - s3:GetBucketRequestPayment
          - s3:GetBucketTagging
          - s3:GetBucketVersioning
          - s3:GetBucketWebsite
          - s3:GetEncryptionConfiguration
          - s3:GetLifecycleConfiguration
          - s3:GetReplicationConfiguration
          - s3:ListBucket
          - s3:PutBucketAcl
          - s3:PutBucketTagging
          - s3:PutEncryptionConfiguration
          Resource: 'arn:aws:s3:::*'
        - 
          Effect: Allow
          Action:
          - s3:DeleteObject
          - s3:GetObject
          - s3:GetObjectAcl
          - s3:GetObjectTagging
          - s3:GetObjectVersion
          - s3:PutObject
          - s3:PutObjectAcl
          - s3:PutObjectTagging
          Resource: arn:aws:s3:::*/*
        - 
          Effect: Allow
          Action:
          - ec2:DeleteVolume
          - elasticloadbalancing:DeleteTargetGroup
          - iam:DeleteAccessKey
          - iam:DeleteUser
          - iam:ListInstanceProfiles
          - iam:ListRolePolicies
          - iam:ListUserPolicies
          - s3:ListBucketVersions
          Resource:
          - "arn:aws:iam::*:instance-profile/*",
          - "arn:aws:iam::*:user/*",
          - "arn:aws:iam::*:role/*",
          - "arn:aws:s3:::*",
          - "arn:aws:elasticloadbalancing:*:*:targetgroup/*/*",
          - "arn:aws:ec2:*:*:volume/*"
        - 
          Effect: Allow
          Action:
          - autoscaling:DescribeAutoScalingGroups
          - ec2:DeleteNetworkInterface
          - elasticloadbalancing:DescribeTargetGroups
          - tag:GetResources
          Resource: '*'
        - 
          Effect: Allow
          Action:
          - s3:DeleteObject
          Resource: arn:aws:s3:::*/*
        - 
          Effect: Allow
          Action:
          - ec2:DeleteDhcpOptions
          - ec2:DeleteInternetGateway
          - ec2:DeleteRoute
          - ec2:DeleteRouteTable
          - ec2:DeleteVpcEndpoints
          Resource:
          - "arn:aws:ec2:*:*:route-table/*"
          - "arn:aws:ec2:*:*:vpc-endpoint/*"
          - "arn:aws:ec2:*:*:dhcp-options/*"
          - "arn:aws:ec2:*:*:internet-gateway/*"
        - 
          Effect: Allow
          Action:
          - ec2:DeleteNatGateway
          - ec2:DeleteSubnet
          - ec2:DeleteVpc
          - ec2:DetachInternetGateway
          - ec2:DisassociateRouteTable
          - ec2:ReplaceRouteTableAssociation
          Resource: '*'
        - 
          Effect: Allow
          Action:
          - iam:CreateAccessKey
          - iam:CreateUser
          - iam:DeleteAccessKey
          - iam:DeleteUser
          - iam:DeleteUserPolicy
          - iam:GetUserPolicy
          - iam:ListAccessKeys
          - iam:PutUserPolicy
          - iam:TagUser
          Resource: arn:aws:iam::*:user/*
        - 
          Effect: Allow
          Action:
          - s3:GetBucketPublicAccessBlock
          - s3:ListBucketMultipartUploads
          - s3:PutBucketPublicAccessBlock
          - s3:PutLifecycleConfiguration
          Resource: arn:aws:s3:::*
        - 
          Effect: Allow
          Action:
          - s3:AbortMultipartUpload
          Resource: arn:aws:s3:::*/*
        - 
          Effect: Allow
          Action:
          - s3:HeadBucket
          Resource: '*'
        Version: '2012-10-17'
    Type: AWS::IAM::ManagedPolicy

  User:
    DependsOn: Group
    Properties:
      Groups:
      - !Ref Group
    Type: AWS::IAM::User

